import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import Script from "next/script";
import "../styles/globals.css";
import "../styles/scss/bootstrap.scss";
import "../styles/Footer.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Rozhok</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
